<?php

/**
 * @file
 * Updates Drupal to use the latest version of jQuery.
 */

/**
 * Implements hook_help().
 */
function greenhouse_menu() {
        $items['Addsensor'] = array(
                'title'=>'Add sensor',
                'page callback' => 'greenhouse_add_sensor',
                'access arguments' => array('Add delete Sensor'),
                'menu_name' => 'main-menu',
            );
        return $items;
}

function greenhouse_add_sensor() {
/*    $form = array();
    $form['addsensor'] = array(
        '#title' => t('test'),
        '#type' => 'textarea',
        '#description' => t ('test'),
        '#default_value' => t('test'),
        '#value' => t(''),
        );
    return $form;*/
    return 'test';
}

function greenhouse_permission() {
  return array(
    'Add delete Sensor' => array(
      'description' => t('Add an sensor'),
      'title' => t('Add/delete Sensor'),
      'restrict access' => TRUE,
    ),
  );
}