<?php

/**
 * @file
 * Updates Drupal to use the latest version of jQuery.
 */

/**
 * Implements hook_help().
 */
function greenhouse_menu() {
    $items['greenhouse/sensors'] = array(
        'title' => 'Sensors',
        'page callback' => 'greenhouse_sensor',
        'file' =>'includes/sensor.inc',
        'menu_name' => 'main-menu',
        'access arguments' => array('Add delete Sensor'),
        'weight' => 20
    );
    
    $items['greenhouse/power'] = array(
        'title' => 'Power',
        'page callback' => 'greenhouse_power',
        'file' =>'includes/power.inc',
        'menu_name' => 'main-menu',
        'access arguments' => array('Add delete Sensor'),
        'weight' => 25
    );
    
    $items['greenhouse/power/delete/%'] = array(
        'title' => 'Delete',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('greenhouse_delete_power',3),
        'file' =>'includes/power.inc',
        'access arguments' => array('Add delete Sensor'),
    );
    
    $items['greenhouse/sensors/delete/%'] = array(
        'title' => 'Delete',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('greenhouse_delete_sensor',3),
        'file' =>'includes/sensor.inc',
        'access arguments' => array('Add delete Sensor'),
        'weight' => 25
    );
    
    $items['greenhouse/sensor/update/%'] = array(
        'title' => 'Edit Sensor',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('greenhouse_update_sensor',3),
        'file' =>'includes/sensor.inc',
        'access arguments' => array('Add delete Sensor'),
    );
 
     $items['greenhouse/power/update/%'] = array(
        'title' => 'Edit Power',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('greenhouse_update_power',3),
        'file' =>'includes/power.inc',
        'access arguments' => array('Add delete Sensor'),
    );
    
    $items['greenhouse/information'] = array(
        'title' => 'Infomation',
        'page callback' => 'greenhouse_infomation',
        'access arguments' => array('View sensor data'),
        'file' =>'includes/information.inc',
        'menu_name' => 'main-menu',
    );
    
    $items['greenhouse/information/sensors/%'] = array(
        'title' => 'More Infomation',
        'file' =>'includes/information.inc',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('greenhouse_infomation_sensor_date_form',3),
        'access arguments' => array('View sensor data'),
    );
    
    $items['greenhouse/information/sensors/data/%/%/%'] = array(
        'title' => 'More Infomation',
        'file' =>'includes/information.inc',
        'page callback' => 'greenhouse_infomation_sensor_viewmore',
        'page arguments' => array(4,5,6),
        'access arguments' => array('View sensor data'),
    );
        
    $items['admin/config/system/greenhouse'] = array(
        'title' => 'Greenhouse settings',
        'page callback' => 'greenhouse_settings',
        'file' =>'includes/admin.setting.inc',
        'access arguments' => array('Change Setting'),
    );
    return $items;
}


function greenhouse_permission() {
  return array(
    'Add delete Sensor' => array(
      'description' => t('Add an sensor'),
      'title' => t('Add/delete Sensor'),
      'restrict access' => TRUE,
    ),
    'View sensor data' => array(
      'description' => t('View sensor data'),
      'title' => t('View sensor data'),
      'restrict access' => TRUE,
    ),
    'Change Setting' => array(
      'description' => t('Change Setting'),
      'title' => t('Change Setting'),
      'restrict access' => TRUE,
    ),
  );
}
